version: '3.11'

services:
  meditation-app:
    depends_on:
      - mindfulness-app-db
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mindfulness:/mindfulness/
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000


  mindfulness-app-db:
    image: postgres:13
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres-data:
