version: '3.11'

services:
  meditation-app:
    build:
      context: .
    volumes:
      - static-data:/vol/static
    environment:
      - DB_HOST=db
      - DB_NAME={DB_NAME}
      - DB_USER={DB_USER}
      - DB_PASS={DB_PASS}
      - SECRET_KEY={DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS={DJANGO_ALLOWED_HOSTS}
    depends_on:
      - mindfulness-app-db
    restart: always


  mindfulness-app-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASS}
      - POSTGRES_DB={DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always


  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - meditation-app
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: