# Generated by Django 4.2.1 on 2023-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_customchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='time_duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
